services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - .env
    volumes:
      - ./libs:/app/libs
      - ./apps/web:/app/apps/web

  api-bookings:
    build:
      context: .
      dockerfile: apps/api-bookings/Dockerfile
    env_file:
      - .env
    volumes:
      - ./libs:/app/libs
      - ./apps/api-bookings:/app/apps/api-bookings
    expose:
      - "4003"

  api-products:
    build:
      context: .
      dockerfile: apps/api-products/Dockerfile
    env_file:
      - .env
    volumes:
      - ./libs:/app/libs
      - ./apps/api-products:/app/apps/api-products
    expose:
      - "4002"

  api-analytics:
    build:
      context: .
      dockerfile: apps/api-analytics/Dockerfile
    volumes:
      - ./apps/api-analytics:/app/apps/api-analytics
    expose:
      - "4011"

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro


volumes:
  pgdata:
